# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fixtures.proto

require 'google/protobuf'

require 'google/protobuf/wrappers_pb'
require 'google/protobuf/timestamp_pb'


descriptor_data = "\n\x0e\x66ixtures.proto\x12\x0bpb.fixtures\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x01\n\x06ProtoA\x12\n\n\x02id\x18\x01 \x01(\x03\x12*\n\x04name\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12$\n\x07proto_b\x18\x04 \x01(\x0b\x32\x13.pb.fixtures.ProtoB\"\x14\n\x06ProtoB\x12\n\n\x02id\x18\x01 \x01(\x03\x62\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Pb
  module Fixtures
    ProtoA = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.fixtures.ProtoA").msgclass
    ProtoB = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pb.fixtures.ProtoB").msgclass
  end
end
